import ReactQueryProvider from '@/providers/reactQueryProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import CartProvider from '@/providers/cartProvider'
import { AES, enc } from 'crypto-js';
import { cookies } from 'next/headers';
import { queryClient } from '@/lib/reactQuery/queryClient'
import { getUser } from '@/lib/axios'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'shop laptop',
  description: 'Generated by create next app',
}
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <CartProvider>
            {children}
          </CartProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
